### ISSUE TITLE
Config option to force protocol

### ISSUE THREAD

**Issue by JohnRiv** [jumph4x/canonical-rails#13]
What are your thoughts on including a config option to force the protocol for the canonical URL href? For example, a site could have the same content hosted on http & https and wants to always have https be the canonical URL. With the current setup, the protocol is based on the incoming request protocol.

If you agree that is useful, I can work on a pull request.

**Comment by jumph4x** [comment]
Do it up.

**Comment by jumph4x** [comment]
https://rubygems.org/gems/canonical-rails/versions/0.0.8
