### ISSUE TITLE
It ignores parameters with numerical values

### ISSUE THREAD

**Issue by IslamAzab** [jumph4x/canonical-rails#15]
My `canonical_rails.rb` file:
```
config.collection_actions = [:index]
config.whitelisted_parameters = [:page, :room_id, :style]
```

For this url:
**http://www.example.com/model?room_id=1&style=all&utf8=✓**

canonical tag generates the following :
**http://www.example.com/model/?room_id&style=all&page**

while I expect something like this
**http://www.example.com/model?room_id=1&style=all&page=1**

**Comment by IslamAzab** [comment]
The problem is mainly here so far
[`Rack::Utils.build_nested_query(whitelisted_params)`](https://github.com/jumph4x/canonical-rails/blob/eedf68426a40d848e0e577010d1f443e9aa5e9a0/app/helpers/canonical_rails/tag_helper.rb#L40)

**Comment by jumph4x** [comment]
Hmm, noted.

**Comment by jumph4x** [comment]
Handled.

**Comment by jumph4x** [comment]
Update to https://rubygems.org/gems/canonical-rails/versions/0.0.9
