### ISSUE TITLE
Missleading documenation

### ISSUE THREAD

**Issue by mmorava** [jumph4x/canonical-rails#17]
Hi !

Not a big deal, but I think current documentation is a bit misleading and could cause problems for some developers. Canonical tag should be always put in the HTTP header or in the head tag of the HTML document. Current README suggest putting canonical_tag "into the views" which I think should be changed to "head section of your layout file".

Putting canonical tag into the body is listed as mistake number 5 at http://googlewebmastercentral.blogspot.ie/2013/04/5-common-mistakes-with-relcanonical.html

**Comment by jumph4x** [comment]
You're right, not everyone would know that meta tags go into the `head`. Fix in a4f65e20dcad6577111373709b7ee47c0675b625
