### ISSUE TITLE
Canonical url does not include port number

### ISSUE THREAD

**Issue by andrewjaanuu** [jumph4x/canonical-rails#21]
Canonical url does not include port number on the host.

**Comment by jumph4x** [comment]
PRs welcome!

**Comment by jumph4x** [comment]
bump @andrewjaanuu

**Comment by jgillman** [comment]
Is there a way to *not* include the port number? I'm not able to find any documentation that says it's better/worse to include it but every example I'm finding when searching leaves off the port number unless it's non-standard or important for a specific use case.

**Comment by olasile** [comment]
> Is there a way to _not_ include the port number? I'm not able to find any documentation that says it's better/worse to include it but every example I'm finding when searching leaves off the port number unless it's non-standard or important for a specific use case.

To exclude the port number, put this in `config/initializers/canonical_rails.rb`.

`CanonicalRails::TagHelper.module_eval do
  def canonical_href(host = canonical_host, port = canonical_port)
    port = port.present? && port.to_i != 80 ? ":#{port}" : ''
    raw "#{canonical_protocol}#{host}#{path_without_html_extension}#{trailing_slash_if_needed}#{whitelisted_query_string}".downcase
  end
end`

**Comment by FrantisekVrab** [comment]
> 
> 
> > Is there a way to _not_ include the port number? I'm not able to find any documentation that says it's better/worse to include it but every example I'm finding when searching leaves off the port number unless it's non-standard or important for a specific use case.
> 
> To exclude the port number, put this in `config/initializers/canonical_rails.rb`.
> 
> ```
> CanonicalRails::TagHelper.module_eval do
>   def canonical_href(host = canonical_host, port = canonical_port)
>     port = port.present? && port.to_i != 80 ? ":#{port}" : ''
>     raw "#{canonical_protocol}#{host}#{path_without_html_extension}#{trailing_slash_if_needed}#{whitelisted_query_string}".downcase
>   end
> end
> ```

thanks, works, but there should be some config to not include it, like 

```
  config.port = nil
  config.port = false
  config.port = ''
```

am i wrong? i haven't found anything like this working

**Comment by mdegoys** [comment]
Olasile solution doesn't work for me, and maybe it would be better to have a parameter to avoid using ports ? Or even by default not using port ?
