### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by samuelpismel** [jumph4x/canonical-rails#29]
Nice gem man! Thanks for doing that!

Can you improve the read-me file to something like this article?
[http://blog.planetargon.com/entries/2014/4/4/easily-add-canonical-urls-to-your-rails-app](http://blog.planetargon.com/entries/2014/4/4/easily-add-canonical-urls-to-your-rails-app)

The current read-me is not so clear.

Thanks!

**Comment by jumph4x** [comment]
Added a mention in 36577aa591fc6fdc8ec9d235230feb32ea35e183
