### ISSUE TITLE
No Route matches for canonical

### ISSUE THREAD

**Issue by thebravoman** [jumph4x/canonical-rails#30]
I have been using canonical for quite some time, but it just stopped working after migrating to devise 4.2.0. This is preparation for rails 5

It only happens in the the rspec.

```
<link href="http://mysiteno route matches {:action=>"application", :controller=>"layouts"}" rel="canonical" />
```

The code i have debugged is:

```
   11:     def path_without_html_extension
=> 12:       request.path.sub(/\.html$/, '')
   13:     end
```

and here the request.path returns 

```
"No route matches {:action=>\"application\", :controller=>\"layouts\"}"
```

Not sure where to go from here.

**Comment by krzysiek1507** [comment]
Hi @thebravoman could you provide more details?

**Comment by thebravoman** [comment]
@krzysiek1507 Yes, of course. It is now updated. Some problem with github editor - was not displaying part of the text..

**Comment by krzysiek1507** [comment]
@thebravoman action and controller look very weird. Are you sure if there are no problems with your code or with devise routes/controllers/actions?

**Comment by jumph4x** [comment]
Rails 5 build passed with no issues: https://travis-ci.org/jumph4x/canonical-rails/builds/143236938

**Comment by thebravoman** [comment]
@krzysiek1507 
I am not sure.

This is the code in the application.html.erb

```
<%= canonical_tag -%>
```

In production it seems to. But the test is 

```
it "canonical_tag" do
			render
			expect(rendered).to have_xpath "//link[@href='http://example.com'][@rel='canonical']", visible: false
		end
``` 

The content of the rendered page is 

```
<link href="http://example.comno route matches {:action=>"application", :controller=>"layouts"}" rel="canonical" />
```

What could I check next?

**Comment by jumph4x** [comment]
@thebravoman resolved?

**Comment by thebravoman** [comment]
I've reworked this part of the app. The error is not currently occurring so yes.. resolved @jumph4x
