### ISSUE TITLE
What if I add the tag without the gem? [question]

### ISSUE THREAD

**Issue by ClaudioCarmeli** [jumph4x/canonical-rails#39]
In `app/views/layouts/application.html.erb` I have:
```
  <link rel="canonical" href="https://www.my-domain.com" />
```

Would it be any different if I had, instead:
```
  <%= canonical_tag -%>
```
?

**Comment by jumph4x** [comment]
That's a pretty broad question. I recommend going through the README as a start. 

Short answer is: do not simply have a homepage URL specified as a canonical for the entire webapp.
