### ISSUE TITLE
add_helpers initializer prevents Rails 6.0.0rc1 app initialization

### ISSUE THREAD

**Issue by hwangm** [jumph4x/canonical-rails#54]
Gem version: 0.2.5
Ruby version: 2.6.3
Rails version: 6.0.0rc1

While attempting to upgrade an application from Rails 5.2 to 6.0.0rc1, I ran into this issue related to new autoload logic and an initializer in the canonical-rails engine.rb file:

```
/Users/mhwang/.rvm/gems/ruby-2.6.3/gems/railties-6.0.0.rc1/lib/rails/initializable.rb:32:in `instance_exec': DEPRECATION WARNING: Initialization autoloaded the constant CanonicalRails::TagHelper. (ActiveSupport::DeprecationException)

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload CanonicalRails::TagHelper, for example,
the expected changes won't be reflected in that stale Module object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /Users/mhwang/fuzzy/code/marketing/config/environment.rb:5)
```

The line of code that is the issue is in engine.rb:
```
module CanonicalRails
  class Engine < ::Rails::Engine

    initializer 'canonical_rails.add_helpers' do |app|
      ActionView::Base.send :include, CanonicalRails::TagHelper
    end

  end
end
```

If I remove the initializer, the application loads fine. Without the initializer, the canonical_tag helper still works on each webpage. 

This change is also backwards compatible to Rails 5.2. Is it worth considering removing this initializer for future compatibility if it still works without? Any suggestions would be appreciated!

**Comment by jumph4x** [comment]
@hwangm firstly, thanks for the report. 

Could you do us a favor and checking if the backwards compatibility extends to Rails 4? That'll help me make the decision and I'll get something out there soon.

**Comment by dvandersluis** [comment]
I'm running into this issue in Rails 6 as well.

**Comment by jumph4x** [comment]
Bumping for a PR.

**Comment by mrpinsky** [comment]
@jumph4x https://github.com/jumph4x/canonical-rails/pull/61 solves this problem on Rails 6.0.3.2. I believe that the behavior was always the same (code loaded in initializers doesn't get automatic updates from Rails autoloading), and that Rail 6 is simply making this explicit.
