### ISSUE TITLE
Check if url is canonical?

### ISSUE THREAD

**Issue by molfar** [jumph4x/canonical-rails#66]
Is there any helper to detect if current url is canonical or not?

**Comment by jumph4x** [comment]
Consider creating your own helper method leveraging https://github.com/jumph4x/canonical-rails/blob/master/app/helpers/canonical_rails/tag_helper.rb#L44, something similar to this:

```ruby
def canonical? path
   path == canonical_path
end
```

or 
```ruby
def current_path_canonical? 
   request.path == canonical_path
end
```

**Comment by molfar** [comment]
@jumph4x thanks. May be it would be expedient to include it in gem? For example, my case is implementing Google's recommendation to include rel alternates links to only canonical pages.

**Comment by jumph4x** [comment]
I am hesitant to include extra functionality that the gem itself does not already use. Comment with the documentation/guidelines here and I can do a longer think on it.

**Comment by jumph4x** [comment]
I'm sure this existing in closed issues will help someone out looking to replicate this request, thank you for submitting. Closing.
