### ISSUE TITLE
Rails 6 how to hide a port?

### ISSUE THREAD

**Issue by Winter-Silence** [jumph4x/canonical-rails#67]
Аfter migrating to rails 6 from 5.2, a port was added to the url. How do I hide it?

**Comment by jumph4x** [comment]
I would double check your Gemfile delta to see how many released this gem dependency jumped: https://github.com/jumph4x/canonical-rails/blob/master/app/helpers/canonical_rails/tag_helper.rb#L34-L40

It's likely you're now on the latest version. If that's the case, I would re-generate the config and port over the values.

**Comment by teamok** [comment]
> I'm sorry I didn't answer. Forcibly added nil for the port parameter

can you clarify please ?
i have the same issue and i would like to remove port from the link

**Comment by teamok** [comment]
> Checking in, any luck?

it looks like this for me.  domainname.com/80:xxxxxx
any idea how to proceed ?

**Comment by Winter-Silence** [comment]
> can you clarify please ? i have the same issue and i would like to remove port from the link

I use it like this `canonical_tag('host.name', nil, false)`

**Comment by jumph4x** [comment]
Marking as resolved.
