### ISSUE TITLE
Rails dependency restricted to <= 7 - won't work with 7.0.1

### ISSUE THREAD

**Issue by joelmoss** [jumph4x/canonical-rails#77]
Rails 7.0.1 has just been released, but because canonical-rails uses `rails (>= 4.1, <= 7.0)`, bundler won't allow it.

Please change the dependency to `rails (>= 4.1, < 7.1)`

thx

**Comment by jumph4x** [comment]
Just released `0.2.14` that addresses this: https://rubygems.org/gems/canonical-rails/versions/0.2.14
